# ============================================================
# Contexa AI-Native Zero Trust Security Platform
# ============================================================

contexa:
  saas:
    enabled: true
  llm:
#    chatModelPriority: openai,ollama,anthropic
    chatModelPriority: ollama,openai,anthropic
#    embeddingModelPriority: openai,ollama
    embeddingModelPriority: ollama,openai

#security:
#  zerotrust:
#    mode: SHADOW

hcad:
  enabled: true
  filterOrder: 100
  resource:
    sensitivePatterns:
      - "/admin/api/security-test/sensitive/**"
      - "/admin/api/security-test/critical/**"
      - "/api/security-test/sensitive/**"
      - "/api/security-test/critical/**"
  geoip:
    dbPath: data/GeoLite2-City.mmdb

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/contexa
    username: contexa
    password: contexa1234!@#
    driver-class-name: org.postgresql.Driver

  auth:
    token-transport-type: header_cookie
    oauth2-csrf: false
    token-persistence: localstorage

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:your-anthropic-api-key}
      chat:
        options:
          model: claude-3-sonnet-20240229
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen2.5:7b
          keep-alive: "24h"
      embedding:
        model: mxbai-embed-large
    openai:
      api-key: ${OPENAI_API_KEY:your-anthropic-api-key}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3
    security:
      tiered:
        security:
          trusted-proxy-validation-enabled: true
          trusted-proxies:
            - "127.0.0.1"
            - "::1"
            - "0:0:0:0:0:0:0:1"
    vectorstore:
      pgvector:
        dimensions: 1024
        initialize-schema: true

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
    org.hibernate.orm.connections.pooling: WARN
    org.springframework.aop.framework.CglibAopProxy: ERROR
