package io.contexa.contexaiam.admin.web.studio.service.impl;

import io.contexa.contexaiam.domain.entity.policy.Policy;
import io.contexa.contexaiam.security.xacml.pap.dto.SimulationContext;
import io.contexa.contexaiam.security.xacml.pap.service.PolicyBuilderService;
import io.contexa.contexaiam.admin.web.studio.dto.InitiateGrantRequestDto;
import io.contexa.contexaiam.admin.web.studio.dto.SimulationRequestDto;
import io.contexa.contexaiam.admin.web.studio.dto.SimulationResultDto;
import io.contexa.contexaiam.admin.web.studio.service.StudioActionService;
import io.contexa.contexaiam.admin.web.workflow.wizard.dto.WizardContext;
import io.contexa.contexaiam.admin.web.workflow.wizard.service.PermissionWizardService; 
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.modelmapper.ModelMapper;


@Slf4j
@RequiredArgsConstructor
public class StudioActionServiceImpl implements StudioActionService {

    private final PolicyBuilderService policyBuilderService;
    private final PermissionWizardService permissionWizardService; 
    private final ModelMapper modelMapper;

    
    @Override
    public SimulationResultDto runPolicySimulation(SimulationRequestDto simulationRequest) {
        log.info("Running policy simulation for action: {}", simulationRequest.actionType());
        Policy policyDraft = modelMapper.map(simulationRequest.policyDraft(), Policy.class);
        SimulationContext simulationContext = new SimulationContext(null, null, null);
        return policyBuilderService.simulatePolicy(policyDraft, simulationContext);
    }

    
    @Override
    public WizardContext initiateGrantWorkflow(InitiateGrantRequestDto grantRequest) {
        log.info("Initiating membership management workflow from Studio for users: {}, groups: {}.",
                grantRequest.getUserIds(), grantRequest.getGroupIds());

        
        String autoGeneratedName = "Studio-Membership-Mgmt-" + System.currentTimeMillis();
        String autoGeneratedDesc = String.format("Authorization Studio에서 시작된 멤버십 관리 작업입니다.");

        
        return permissionWizardService.beginCreation(grantRequest, autoGeneratedName, autoGeneratedDesc);
    }
}