/*
 * Copyright 2026 The Contexa Project
 *
 * The Contexa Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package io.contexa.contexaiam.resource.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.contexa.contexaiam.domain.entity.ConditionTemplate;
import io.contexa.contexaiam.resource.service.CompatibilityResult;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Function;

public final class ConditionClassificationDtos {

    private ConditionClassificationDtos() {
    }

    public record ClassifiedConditionsResponse(
            int total,
            ConditionClassificationGroups<ConditionTemplate> byClassification,
            ConditionStatisticsResponse statistics
    ) {
        public static ClassifiedConditionsResponse from(List<ConditionTemplate> conditions) {
            return new ClassifiedConditionsResponse(
                    conditions.size(),
                    ConditionClassificationGroups.from(
                            conditions,
                            ConditionClassificationDtos::classificationOrUniversal),
                    ConditionStatisticsResponse.from(conditions));
        }
    }

    public record CompatibleConditionsResponse(
            Long resourceId,
            String resourceIdentifier,
            ConditionClassificationGroups<ConditionInfoResponse> compatibleConditions,
            int totalCompatible,
            int totalChecked
    ) {
        public static CompatibleConditionsResponse from(
                Long resourceId,
                String resourceIdentifier,
                List<ConditionTemplate> conditions,
                Map<Long, CompatibilityResult> compatibilityResults) {

            List<ConditionInfoResponse> compatible = new ArrayList<>();
            int totalCompatible = 0;

            for (ConditionTemplate condition : conditions) {
                CompatibilityResult result = compatibilityResults.get(condition.getId());
                if (result != null && result.isCompatible()) {
                    compatible.add(ConditionInfoResponse.from(condition, result));
                    totalCompatible++;
                }
            }

            return new CompatibleConditionsResponse(
                    resourceId,
                    resourceIdentifier,
                    ConditionClassificationGroups.from(
                            compatible,
                            ConditionInfoResponse::classification),
                    totalCompatible,
                    conditions.size());
        }
    }

    public record ClassificationUpdateResponse(
            Long conditionId,
            ConditionTemplate.ConditionClassification oldClassification,
            ConditionTemplate.ConditionClassification newClassification,
            boolean updated
    ) {
    }

    public record ConditionStatisticsResponse(
            long autoGenerated,
            long manual,
            double avgComplexityScore
    ) {
        public static ConditionStatisticsResponse from(List<ConditionTemplate> conditions) {
            long autoGenerated = conditions.stream()
                    .mapToLong(condition -> Boolean.TRUE.equals(condition.getIsAutoGenerated()) ? 1 : 0)
                    .sum();
            long manual = conditions.size() - autoGenerated;
            double avgComplexityScore = conditions.stream()
                    .mapToInt(condition -> condition.getComplexityScore() != null
                            ? condition.getComplexityScore()
                            : 1)
                    .average()
                    .orElse(0.0);

            return new ConditionStatisticsResponse(autoGenerated, manual, avgComplexityScore);
        }
    }

    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record ConditionClassificationGroups<T>(
            @JsonProperty("UNIVERSAL") List<T> universal,
            @JsonProperty("CONTEXT_DEPENDENT") List<T> contextDependent,
            @JsonProperty("CUSTOM_COMPLEX") List<T> customComplex
    ) {
        public static <T> ConditionClassificationGroups<T> from(
                List<T> items,
                Function<T, ConditionTemplate.ConditionClassification> classifier) {
            List<T> universal = new ArrayList<>();
            List<T> contextDependent = new ArrayList<>();
            List<T> customComplex = new ArrayList<>();

            for (T item : items) {
                switch (classifier.apply(item)) {
                    case UNIVERSAL -> universal.add(item);
                    case CONTEXT_DEPENDENT -> contextDependent.add(item);
                    case CUSTOM_COMPLEX -> customComplex.add(item);
                }
            }

            return new ConditionClassificationGroups<>(
                    nullIfEmpty(universal),
                    nullIfEmpty(contextDependent),
                    nullIfEmpty(customComplex));
        }
    }

    public record ConditionInfoResponse(
            Long id,
            String name,
            String description,
            ConditionTemplate.ConditionClassification classification,
            Integer complexityScore,
            Boolean approvalRequired,
            String compatibilityReason
    ) {
        public static ConditionInfoResponse from(ConditionTemplate condition, CompatibilityResult result) {
            return new ConditionInfoResponse(
                    condition.getId(),
                    condition.getName(),
                    condition.getDescription(),
                    condition.getClassification(),
                    condition.getComplexityScore(),
                    condition.getApprovalRequired(),
                    result.getReason());
        }
    }

    public sealed interface ConditionTemplateGenerationResponse
            permits NoManagedResourceResponse,
                    RegeneratedTemplatesResponse,
                    GeneratedTemplatesResponse,
                    ConditionTemplateGenerationErrorResponse {
    }

    public record NoManagedResourceResponse(
            boolean success,
            String error,
            String message,
            long resourceCount
    ) implements ConditionTemplateGenerationResponse {
    }

    public record RegeneratedTemplatesResponse(
            boolean success,
            boolean deletedOldTemplates,
            int generatedCount,
            String message,
            List<RegeneratedTemplateResponse> templates
    ) implements ConditionTemplateGenerationResponse {
        public static RegeneratedTemplatesResponse success(List<ConditionTemplate> templates) {
            return new RegeneratedTemplatesResponse(
                    true,
                    true,
                    templates.size(),
                    "Cleaned up invalid conditions and regenerated correct condition templates",
                    templates.stream()
                            .map(RegeneratedTemplateResponse::from)
                            .toList());
        }
    }

    public record GeneratedTemplatesResponse(
            boolean success,
            int generatedCount,
            String message,
            List<GeneratedTemplateResponse> templates
    ) implements ConditionTemplateGenerationResponse {
        public static GeneratedTemplatesResponse success(
                List<ConditionTemplate> templates,
                String message) {
            return new GeneratedTemplatesResponse(
                    true,
                    templates.size(),
                    message,
                    templates.stream()
                            .map(GeneratedTemplateResponse::from)
                            .toList());
        }
    }

    public record ConditionTemplateGenerationErrorResponse(
            boolean success,
            String error,
            String message
    ) implements ConditionTemplateGenerationResponse {
        public static ConditionTemplateGenerationErrorResponse from(Exception exception, String message) {
            return new ConditionTemplateGenerationErrorResponse(false, exception.getMessage(), message);
        }
    }

    public record RegeneratedTemplateResponse(
            Long id,
            String name,
            String description,
            String spelTemplate,
            ConditionTemplate.ConditionClassification classification
    ) {
        public static RegeneratedTemplateResponse from(ConditionTemplate template) {
            return new RegeneratedTemplateResponse(
                    Objects.requireNonNull(template.getId()),
                    Objects.requireNonNull(template.getName()),
                    Objects.requireNonNull(template.getDescription()),
                    Objects.requireNonNull(template.getSpelTemplate()),
                    Objects.requireNonNull(template.getClassification()));
        }
    }

    public record GeneratedTemplateResponse(
            Long id,
            String name,
            String description,
            ConditionTemplate.ConditionClassification classification,
            String sourceMethod
    ) {
        public static GeneratedTemplateResponse from(ConditionTemplate template) {
            return new GeneratedTemplateResponse(
                    Objects.requireNonNull(template.getId()),
                    Objects.requireNonNull(template.getName()),
                    Objects.requireNonNull(template.getDescription()),
                    Objects.requireNonNull(template.getClassification()),
                    Objects.requireNonNull(template.getSourceMethod()));
        }
    }

    private static ConditionTemplate.ConditionClassification classificationOrUniversal(ConditionTemplate condition) {
        return condition.getClassification() != null
                ? condition.getClassification()
                : ConditionTemplate.ConditionClassification.UNIVERSAL;
    }

    private static <T> List<T> nullIfEmpty(List<T> values) {
        return values.isEmpty() ? null : values;
    }
}
