package io.contexa.demo.scenario.domain;

public enum Selector {
    ASSIGNED_PROJECTS,
    ASSIGNED_PROJECT_DOCUMENTS,
    VALID_BULK_APPROVAL,
    APPROVED_PROJECT_DOCUMENTS,
    VALID_EMERGENCY_APPROVAL,
    EXCEPTION_APPROVED_DOCUMENTS,
    VISIBLE_PROJECTS,
    UNASSIGNED_PROJECT_DOCUMENTS,
    UNASSIGNED_CUSTOMER_SCOPE,
    PREVIOUSLY_READ_UNASSIGNED_DOCUMENTS,
    DOCUMENT_WITH_UNTRUSTED_INSTRUCTION
}
