package io.contexa.contexaiam.resource.controller;

import io.contexa.contexacommon.entity.ManagedResource;
import io.contexa.contexaiam.domain.entity.ConditionTemplate;
import io.contexa.contexaiam.repository.ConditionTemplateRepository;
import io.contexa.contexaiam.repository.ManagedResourceRepository;
import io.contexa.contexaiam.resource.service.AutoConditionTemplateService;
import io.contexa.contexaiam.resource.service.CompatibilityResult;
import io.contexa.contexaiam.resource.service.ConditionCompatibilityService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@ExtendWith(MockitoExtension.class)
@DisplayName("ConditionClassificationController DTO boundary")
class ConditionClassificationControllerDtoBoundaryTest {

    @Mock
    private ConditionTemplateRepository conditionTemplateRepository;

    @Mock
    private ManagedResourceRepository managedResourceRepository;

    @Mock
    private ConditionCompatibilityService compatibilityService;

    @Mock
    private AutoConditionTemplateService autoConditionTemplateService;

    @Test
    @DisplayName("classified conditions preserves existing response JSON")
    void classifiedConditionsPreservesExistingResponseJson() throws Exception {
        when(conditionTemplateRepository.findAll()).thenReturn(List.of(
                condition(1L, "universal", ConditionTemplate.ConditionClassification.UNIVERSAL, true),
                condition(2L, "custom", ConditionTemplate.ConditionClassification.CUSTOM_COMPLEX, false)));

        newMockMvc().perform(get("/admin/api/conditions/classified"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.total").value(2))
                .andExpect(jsonPath("$.byClassification.UNIVERSAL[0].name").value("universal"))
                .andExpect(jsonPath("$.byClassification.CUSTOM_COMPLEX[0].name").value("custom"))
                .andExpect(jsonPath("$.statistics.autoGenerated").value(1))
                .andExpect(jsonPath("$.statistics.manual").value(1))
                .andExpect(jsonPath("$.statistics.avgComplexityScore").value(1.0));
    }

    @Test
    @DisplayName("compatible conditions preserves existing response JSON")
    void compatibleConditionsPreservesExistingResponseJson() throws Exception {
        ManagedResource resource = ManagedResource.builder()
                .id(10L)
                .resourceIdentifier("UserController.list")
                .resourceType(ManagedResource.ResourceType.METHOD)
                .friendlyName("User list")
                .build();
        ConditionTemplate template = condition(1L, "universal", ConditionTemplate.ConditionClassification.UNIVERSAL, false);

        when(managedResourceRepository.findById(10L)).thenReturn(Optional.of(resource));
        when(conditionTemplateRepository.findAll()).thenReturn(List.of(template));
        when(compatibilityService.checkBatchCompatibility(any(), eq(resource)))
                .thenReturn(Map.of(1L, new CompatibilityResult(
                        true,
                        "compatible",
                        Set.of(),
                        Set.of("authentication"),
                        ConditionTemplate.ConditionClassification.UNIVERSAL,
                        false)));

        newMockMvc().perform(get("/admin/api/conditions/compatible/10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.resourceId").value(10))
                .andExpect(jsonPath("$.resourceIdentifier").value("UserController.list"))
                .andExpect(jsonPath("$.compatibleConditions.UNIVERSAL[0].name").value("universal"))
                .andExpect(jsonPath("$.compatibleConditions.UNIVERSAL[0].compatibilityReason").value("compatible"))
                .andExpect(jsonPath("$.totalCompatible").value(1))
                .andExpect(jsonPath("$.totalChecked").value(1));
    }

    @Test
    @DisplayName("classification update preserves existing response JSON")
    void classificationUpdatePreservesExistingResponseJson() throws Exception {
        ConditionTemplate template = condition(1L, "condition", ConditionTemplate.ConditionClassification.UNIVERSAL, false);
        when(conditionTemplateRepository.findById(1L)).thenReturn(Optional.of(template));

        newMockMvc().perform(put("/admin/api/conditions/1/classification")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "classification": "CUSTOM_COMPLEX",
                                  "approvalRequired": true,
                                  "contextDependent": true,
                                  "complexityScore": 8
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.conditionId").value(1))
                .andExpect(jsonPath("$.oldClassification").value("UNIVERSAL"))
                .andExpect(jsonPath("$.newClassification").value("CUSTOM_COMPLEX"))
                .andExpect(jsonPath("$.updated").value(true));

        verify(conditionTemplateRepository).save(template);
    }

    @Test
    @DisplayName("regenerate fixed templates preserves no-resource error JSON")
    void regenerateFixedTemplatesPreservesNoResourceErrorJson() throws Exception {
        when(managedResourceRepository.count()).thenReturn(0L);

        newMockMvc().perform(post("/admin/api/conditions/regenerate-fixed-templates"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.error").value("No ManagedResource data found"))
                .andExpect(jsonPath("$.message").value("Please run resource scan first"))
                .andExpect(jsonPath("$.resourceCount").value(0));
    }

    @Test
    @DisplayName("generate managed-resource templates preserves success JSON")
    void generateManagedResourceTemplatesPreservesSuccessJson() throws Exception {
        when(autoConditionTemplateService.generateConditionTemplates()).thenReturn(List.of(
                condition(7L, "generated", ConditionTemplate.ConditionClassification.CONTEXT_DEPENDENT, true)));

        newMockMvc().perform(post("/admin/api/conditions/generate-managed-resource-based"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.generatedCount").value(1))
                .andExpect(jsonPath("$.message").value("ManagedResource-based condition templates have been successfully generated"))
                .andExpect(jsonPath("$.templates[0].id").value(7))
                .andExpect(jsonPath("$.templates[0].name").value("generated"))
                .andExpect(jsonPath("$.templates[0].classification").value("CONTEXT_DEPENDENT"))
                .andExpect(jsonPath("$.templates[0].sourceMethod").value("source.generated"));
    }

    private MockMvc newMockMvc() {
        return MockMvcBuilders
                .standaloneSetup(new ConditionClassificationController(
                        conditionTemplateRepository,
                        managedResourceRepository,
                        compatibilityService,
                        autoConditionTemplateService))
                .build();
    }

    private static ConditionTemplate condition(
            Long id,
            String name,
            ConditionTemplate.ConditionClassification classification,
            boolean autoGenerated) {
        return ConditionTemplate.builder()
                .id(id)
                .name(name)
                .description(name + " description")
                .spelTemplate("true")
                .classification(classification)
                .complexityScore(1)
                .approvalRequired(false)
                .isAutoGenerated(autoGenerated)
                .sourceMethod("source." + name)
                .build();
    }
}
