package io.contexa.contexaiam.resource.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.contexa.contexacore.std.operations.AINativeProcessor;
import io.contexa.contexaiam.aiam.protocol.request.ConditionTemplateGenerationRequest;
import io.contexa.contexaiam.aiam.protocol.response.ConditionTemplateGenerationResponse;
import io.contexa.contexaiam.domain.dto.AutoGeneratedTemplate;
import io.contexa.contexaiam.domain.entity.ConditionTemplate;
import io.contexa.contexaiam.repository.ConditionTemplateRepository;
import io.contexa.contexaiam.repository.ManagedResourceRepository;
import io.contexa.contexaiam.resource.MethodPatternAnalyzer.MethodAnalysisResult;
import io.contexa.contexacommon.entity.ManagedResource;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@RequiredArgsConstructor
@Slf4j
public class AutoConditionTemplateService {

    private final ConditionTemplateRepository conditionTemplateRepository;
    private final ManagedResourceRepository managedResourceRepository;
    private final AINativeProcessor aiNativeProcessor;
    private final ObjectMapper objectMapper;

    

    


    
    @Transactional
    public List<ConditionTemplate> generateTemplatesFromAnalysis(List<MethodAnalysisResult> analysisResults) {
        log.info("자동 조건 템플릿 생성 시작: {} 개 분석 결과", analysisResults.size());

        
        List<ConditionTemplate> universalTemplates = generateUniversalTemplates();
        List<ConditionTemplate> generatedTemplates = new ArrayList<>(universalTemplates);

        
        for (MethodAnalysisResult analysis : analysisResults) {
            List<ConditionTemplate> methodTemplates = generateMethodSpecificTemplates(analysis);
            generatedTemplates.addAll(methodTemplates);
        }

        
        List<ConditionTemplate> savedTemplates = saveDedupedTemplates(generatedTemplates);

        log.info("자동 조건 템플릿 생성 완료: {} 개 템플릿 저장", savedTemplates.size());
        return savedTemplates;
    }

    
    private List<ConditionTemplate> generateUniversalTemplates() {
        List<AutoGeneratedTemplate> universalTemplates = Arrays.asList(
                
                new AutoGeneratedTemplate(
                        "업무시간 접근",
                        "평일 오전 9시부터 오후 6시까지만 접근 허용",
                        "T(java.time.LocalTime).now().hour >= 9 and T(java.time.LocalTime).now().hour <= 18",
                        "universal", "system_generated", true),

                new AutoGeneratedTemplate(
                        "평일 접근",
                        "월요일부터 금요일까지만 접근 허용",
                        "T(java.time.LocalDate).now().dayOfWeek.value <= 5",
                        "universal", "system_generated", true),

                
                new AutoGeneratedTemplate(
                        "내부망 접근",
                        "192.168.x.x 대역에서만 접근 허용",
                        "#request.remoteAddr matches '^192\\\\.168\\\\..*'",
                        "universal", "system_generated", true),

                new AutoGeneratedTemplate(
                        "사내망 접근",
                        "10.x.x.x 대역에서만 접근 허용",
                        "#request.remoteAddr matches '^10\\\\..*'",
                        "universal", "system_generated", true),

                
                new AutoGeneratedTemplate(
                        "인증된 사용자",
                        "로그인한 사용자만 접근 허용",
                        "isAuthenticated()",
                        "universal", "system_generated", true),

                new AutoGeneratedTemplate(
                        "완전 인증된 사용자",
                        "완전히 인증된 사용자만 접근 허용 (Remember-me 제외)",
                        "isFullyAuthenticated()",
                        "universal", "system_generated", true)
        );

        return universalTemplates.stream()
                .map(this::convertToConditionTemplate)
                .collect(Collectors.toList());
    }

    
    private List<ConditionTemplate> generateMethodSpecificTemplates(MethodAnalysisResult analysis) {
        List<AutoGeneratedTemplate> templates = new ArrayList<>();

        switch (analysis.getDetectedPattern()) {
            case OBJECT_RETURN_PATTERN:
                templates.addAll(generateObjectReturnTemplates(analysis));
                break;
            case ID_PARAMETER_PATTERN:
                templates.addAll(generateIdParameterTemplates(analysis));
                break;
            case UNIVERSAL_PATTERN:
                
                break;
            default:
                log.debug("지원하지 않는 패턴으로 템플릿 생성 스킵: {}", analysis.getDetectedPattern());
        }

        return templates.stream()
                .map(this::convertToConditionTemplate)
                .collect(Collectors.toList());
    }

    
    private List<AutoGeneratedTemplate> generateObjectReturnTemplates(MethodAnalysisResult analysis) {
        String entityType = (String) analysis.getMetadata().get("entityType");
        String methodId = analysis.getMethodIdentifier();

        
        String koreanEntityName = getKoreanEntityName(entityType);
        String methodName = extractMethodName(methodId);

        return Arrays.asList(
                new AutoGeneratedTemplate(
                        String.format("특정 %s 읽기 권한", koreanEntityName),
                        String.format("조회된 특정 %s 객체에 대한 개별 읽기 권한을 확인합니다 [메서드: %s]", koreanEntityName, methodName),
                        "hasPermission(#returnObject, 'READ')",
                        "object_return", methodId, false),

                new AutoGeneratedTemplate(
                        String.format("특정 %s 수정 권한", koreanEntityName),
                        String.format("조회된 특정 %s 객체에 대한 개별 수정 권한을 확인합니다 [메서드: %s]", koreanEntityName, methodName),
                        "hasPermission(#returnObject, 'UPDATE')",
                        "object_return", methodId, false),

                new AutoGeneratedTemplate(
                        String.format("특정 %s 삭제 권한", koreanEntityName),
                        String.format("조회된 특정 %s 객체에 대한 개별 삭제 권한을 확인합니다 [메서드: %s]", koreanEntityName, methodName),
                        "hasPermission(#returnObject, 'DELETE')",
                        "object_return", methodId, false)
        );
    }

    
    private List<AutoGeneratedTemplate> generateIdParameterTemplates(MethodAnalysisResult analysis) {
        String entityType = (String) analysis.getMetadata().get("entityType");
        String idParamName = (String) analysis.getMetadata().get("idParameterName");
        String methodId = analysis.getMethodIdentifier();

        
        String koreanEntityName = getKoreanEntityName(entityType);
        String actionName = extractActionFromMethod(methodId);

        return Arrays.asList(
                new AutoGeneratedTemplate(
                        String.format("개별 %s %s 권한", koreanEntityName, actionName),
                        String.format("특정 ID의 %s 객체에 대한 개별 %s 권한을 확인합니다", koreanEntityName, actionName),
                        String.format("hasPermission(#%s, '%s', 'UPDATE')", idParamName, entityType.toUpperCase()),
                        "id_parameter", methodId, false),

                new AutoGeneratedTemplate(
                        String.format("개별 %s 삭제 권한", koreanEntityName),
                        String.format("특정 ID의 %s 객체에 대한 개별 삭제 권한을 확인합니다", koreanEntityName),
                        String.format("hasPermission(#%s, '%s', 'DELETE')", idParamName, entityType.toUpperCase()),
                        "id_parameter", methodId, false)
        );
    }

    
    private String getKoreanEntityName(String entityType) {
        if (entityType == null || entityType.trim().isEmpty()) {
            return "리소스";
        }

        
        String normalizedType = entityType.trim();
        String lowerType = normalizedType.toLowerCase();

        
        if (lowerType.contains("user")) {
            return "사용자";
        } else if (lowerType.contains("group")) {
            return "그룹";
        } else if (lowerType.contains("role")) {
            return "역할";
        } else if (lowerType.contains("permission")) {
            return "권한";
        } else if (lowerType.contains("policy")) {
            return "정책";
        } else if (lowerType.contains("document")) {
            return "문서";
        } else if (lowerType.contains("file")) {
            return "파일";
        } else if (lowerType.contains("project")) {
            return "프로젝트";
        } else if (lowerType.contains("organization") || lowerType.contains("org")) {
            return "조직";
        } else if (lowerType.contains("department") || lowerType.contains("dept")) {
            return "부서";
        } else if (lowerType.contains("team")) {
            return "팀";
        } else if (lowerType.contains("resource")) {
            return "리소스";
        } else if (lowerType.contains("data")) {
            return "데이터";
        } else if (lowerType.contains("system")) {
            return "시스템";
        } else if (lowerType.contains("service")) {
            return "서비스";
        } else {
            
            return normalizedType.substring(0, 1).toLowerCase() + normalizedType.substring(1);
        }
    }

    
    private String extractActionFromMethod(String methodName) {
        if (methodName == null || methodName.trim().isEmpty()) {
            return "처리";
        }

        String lowerMethod = methodName.toLowerCase().trim();

        
        if (lowerMethod.startsWith("create") || lowerMethod.startsWith("add") ||
                lowerMethod.startsWith("insert") || lowerMethod.startsWith("new") ||
                lowerMethod.startsWith("register") || lowerMethod.startsWith("build")) {
            return "생성";
        } else if (lowerMethod.startsWith("get") || lowerMethod.startsWith("find") ||
                lowerMethod.startsWith("fetch") || lowerMethod.startsWith("retrieve") ||
                lowerMethod.startsWith("select") || lowerMethod.startsWith("search") ||
                lowerMethod.startsWith("load") || lowerMethod.startsWith("read") ||
                lowerMethod.startsWith("view") || lowerMethod.startsWith("show")) {
            return "조회";
        } else if (lowerMethod.startsWith("update") || lowerMethod.startsWith("modify") ||
                lowerMethod.startsWith("edit") || lowerMethod.startsWith("change") ||
                lowerMethod.startsWith("alter") || lowerMethod.startsWith("set")) {
            return "수정";
        } else if (lowerMethod.startsWith("delete") || lowerMethod.startsWith("remove") ||
                lowerMethod.startsWith("drop") || lowerMethod.startsWith("clear") ||
                lowerMethod.startsWith("destroy") || lowerMethod.startsWith("purge")) {
            return "삭제";
        } else if (lowerMethod.startsWith("save") || lowerMethod.startsWith("store") ||
                lowerMethod.startsWith("persist")) {
            return "저장";
        } else if (lowerMethod.startsWith("validate") || lowerMethod.startsWith("check") ||
                lowerMethod.startsWith("verify") || lowerMethod.startsWith("confirm")) {
            return "검증";
        } else if (lowerMethod.startsWith("approve") || lowerMethod.startsWith("accept")) {
            return "승인";
        } else if (lowerMethod.startsWith("reject") || lowerMethod.startsWith("deny") ||
                lowerMethod.startsWith("decline")) {
            return "거부";
        } else if (lowerMethod.startsWith("assign") || lowerMethod.startsWith("grant") ||
                lowerMethod.startsWith("give") || lowerMethod.startsWith("allocate")) {
            return "할당";
        } else if (lowerMethod.startsWith("revoke") || lowerMethod.startsWith("unassign") ||
                lowerMethod.startsWith("withdraw") || lowerMethod.startsWith("cancel")) {
            return "취소";
        } else if (lowerMethod.startsWith("send") || lowerMethod.startsWith("notify") ||
                lowerMethod.startsWith("alert")) {
            return "전송";
        } else if (lowerMethod.startsWith("process") || lowerMethod.startsWith("handle") ||
                lowerMethod.startsWith("execute") || lowerMethod.startsWith("run")) {
            return "처리";
        } else if (lowerMethod.startsWith("count") || lowerMethod.startsWith("calculate") ||
                lowerMethod.startsWith("compute")) {
            return "계산";
        } else if (lowerMethod.startsWith("copy") || lowerMethod.startsWith("clone") ||
                lowerMethod.startsWith("duplicate")) {
            return "복사";
        } else if (lowerMethod.startsWith("move") || lowerMethod.startsWith("transfer")) {
            return "이동";
        } else if (lowerMethod.startsWith("export") || lowerMethod.startsWith("download")) {
            return "내보내기";
        } else if (lowerMethod.startsWith("import") || lowerMethod.startsWith("upload")) {
            return "가져오기";
        } else {
            
            return "처리";
        }
    }

    
    private String extractMethodName(String methodId) {
        if (methodId == null || methodId.trim().isEmpty()) {
            return "unknown";
        }

        try {
            String trimmed = methodId.trim();

            
            int lastDotIndex = trimmed.lastIndexOf('.');
            if (lastDotIndex == -1) {
                
                return extractMethodNameFromSignature(trimmed);
            }

            String methodPart = trimmed.substring(lastDotIndex + 1);
            return extractMethodNameFromSignature(methodPart);

        } catch (Exception e) {
            log.warn("메서드명 추출 실패: {}", methodId, e);
            return "unknown";
        }
    }

    
    private String extractMethodNameFromSignature(String methodSignature) {
        if (methodSignature == null || methodSignature.trim().isEmpty()) {
            return "unknown";
        }

        String trimmed = methodSignature.trim();

        
        int parenIndex = trimmed.indexOf('(');
        if (parenIndex != -1) {
            return trimmed.substring(0, parenIndex).trim();
        }

        
        return trimmed;
    }



    
    private ConditionTemplate convertToConditionTemplate(AutoGeneratedTemplate template) {
        ConditionTemplate entity = new ConditionTemplate();
        entity.setName(template.getName());
        entity.setDescription(template.getDescription());
        entity.setSpelTemplate(template.getSpelTemplate());
        entity.setIsAutoGenerated(true);
        entity.setTemplateType(template.getTemplateType());
        entity.setSourceMethod(template.getSourceMethod());
        entity.setIsUniversal(template.isUniversal());
        entity.setCreatedAt(LocalDateTime.now());
        entity.setUpdatedAt(LocalDateTime.now());

        
        if (template.isUniversal()) {
            
            entity.setClassification(ConditionTemplate.ConditionClassification.UNIVERSAL);
            entity.setRiskLevel(ConditionTemplate.RiskLevel.LOW);
            entity.setComplexityScore(1);
            entity.setApprovalRequired(false);
            entity.setContextDependent(false);
        } else {
            
            switch (template.getTemplateType()) {
                case "object_return", "id_parameter", "ownership" -> {
                    entity.setClassification(ConditionTemplate.ConditionClassification.CONTEXT_DEPENDENT);
                    entity.setRiskLevel(ConditionTemplate.RiskLevel.MEDIUM);
                    entity.setComplexityScore(calculateAutoTemplateComplexity(template.getSpelTemplate()));
                    entity.setApprovalRequired(false); 
                    entity.setContextDependent(true);
                }
                case "self_check" -> {
                    entity.setClassification(ConditionTemplate.ConditionClassification.UNIVERSAL);
                    entity.setRiskLevel(ConditionTemplate.RiskLevel.LOW);
                    entity.setComplexityScore(2);
                    entity.setApprovalRequired(false);
                    entity.setContextDependent(false);
                }
                default -> {
                    entity.setClassification(ConditionTemplate.ConditionClassification.CUSTOM_COMPLEX);
                    entity.setRiskLevel(ConditionTemplate.RiskLevel.HIGH);
                    entity.setComplexityScore(calculateAutoTemplateComplexity(template.getSpelTemplate()));
                    entity.setApprovalRequired(true);
                    entity.setContextDependent(true);
                }
            }
        }

        return entity;
    }

    
    private int calculateAutoTemplateComplexity(String spelTemplate) {
        if (spelTemplate == null) return 1;

        int score = 1;
        String spel = spelTemplate.toLowerCase();

        
        if (spel.contains("haspermission")) score += 2;

        
        score += (spel.length() - spel.replace("#", "").length());

        
        if (spel.contains("&&") || spel.contains("||")) score += 1;

        return Math.min(score, 10);
    }

    
    @Transactional
    public List<ConditionTemplate> saveDedupedTemplates(List<ConditionTemplate> templates) {
        
        List<ConditionTemplate> allExistingTemplates = conditionTemplateRepository.findAll();

        
        Set<String> existingNames = allExistingTemplates.stream()
                .map(ConditionTemplate::getName)
                .collect(Collectors.toSet());

        Set<String> existingSpelTemplates = allExistingTemplates.stream()
                .map(ConditionTemplate::getSpelTemplate)
                .collect(Collectors.toSet());

        
        Set<String> processingNames = new HashSet<>();

        
        List<ConditionTemplate> newTemplates = templates.stream()
                .filter(template -> {
                    
                    if (existingSpelTemplates.contains(template.getSpelTemplate())) {
                        log.debug("SpEL 중복으로 건너뜀: {} -> {}", template.getName(), template.getSpelTemplate());
                        return false;
                    }

                    
                    String originalName = template.getName();
                    String uniqueName = makeUniqueName(originalName, existingNames, processingNames);

                    if (!originalName.equals(uniqueName)) {
                        log.info("이름 중복 해결: '{}' -> '{}'", originalName, uniqueName);
                        template.setName(uniqueName);
                    }

                    
                    processingNames.add(uniqueName);
                    existingNames.add(uniqueName); 

                    return true;
                })
                .collect(Collectors.toList());

        log.info("💾 새로운 템플릿 저장: {} 개 (전체: {} 개, SpEL 중복 제외: {} 개)",
                newTemplates.size(), templates.size(), templates.size() - newTemplates.size());

        return newTemplates.isEmpty() ? new ArrayList<>() : conditionTemplateRepository.saveAll(newTemplates);
    }

    
    private String makeUniqueName(String baseName, Set<String> existingNames, Set<String> processingNames) {
        if (!existingNames.contains(baseName) && !processingNames.contains(baseName)) {
            return baseName;
        }

        
        for (int i = 2; i <= 100; i++) {
            String candidateName = baseName + " (" + i + ")";
            if (!existingNames.contains(candidateName) && !processingNames.contains(candidateName)) {
                return candidateName;
            }
        }

        
        String timestampName = baseName + " (" + System.currentTimeMillis() % 10000 + ")";
        log.warn("고유 이름 생성을 위해 타임스탬프 사용: {}", timestampName);
        return timestampName;
    }

    
    @Transactional
    public List<ConditionTemplate> generateConditionTemplates() {
        log.info("AI 기반 METHOD 리소스 조건 템플릿 생성 시작");

        
        List<ManagedResource> methodResources = managedResourceRepository.findAll()
                .stream()
                .filter(resource -> resource.getResourceType() == ManagedResource.ResourceType.METHOD)
                .filter(resource -> resource.getStatus() != ManagedResource.Status.EXCLUDED)
                .toList();

        if (methodResources.isEmpty()) {
            log.warn("METHOD 타입 리소스가 없습니다. 조건 템플릿을 생성하지 않습니다.");
            return new ArrayList<>();
        }

        log.info("AI 분석 대상 METHOD 리소스: {} 개", methodResources.size());

        
        List<ConditionTemplate> templates = new ArrayList<>(generateAIUniversalTemplates());

        
        Set<String> processedMethodSignatures = new HashSet<>();
        int processedCount = 0;
        int skippedCount = 0;

        for (ManagedResource resource : methodResources) {
            try {
                
                String resourceKey = resource.getResourceIdentifier();

                
                if (processedMethodSignatures.contains(resourceKey)) {
                    log.warn("중복 리소스 건너뛰기: {}", resourceKey);
                    skippedCount++;
                    continue;
                }

                List<ConditionTemplate> methodTemplates = generateAISpecificTemplates(resource);
                templates.addAll(methodTemplates);
                processedMethodSignatures.add(resourceKey);
                processedCount++;

                log.info("리소스 {} 처리 완료: {} 개 조건 생성", resourceKey, methodTemplates.size());

            } catch (Exception e) {
                log.warn("AI 메서드 분석 실패: {} - {}", resource.getResourceIdentifier(), e.getMessage());
                skippedCount++;
            }
        }

        log.info("메서드 처리 결과: 처리됨 {} 개, 건너뜀 {} 개", processedCount, skippedCount);

        
        List<ConditionTemplate> savedTemplates = saveDedupedTemplates(templates);

        log.info("🎉 AI 기반 조건 템플릿 생성 완료: {} 개", savedTemplates.size());
        return savedTemplates;
    }

    
    private List<ConditionTemplate> generateAIUniversalTemplates() {
        log.info("AI 범용 조건 템플릿 생성 시작");

        
        String userPrompt = "서비스 레이어에서 정말 필요한 핵심 범용 조건 4-5개만 생성해주세요.";

        try {
            String aiResponse = callAI("", userPrompt);
            return parseAITemplateResponse(aiResponse, "범용");
        } catch (Exception e) {
            log.error("AI 범용 템플릿 생성 실패", e);
            return generateFallbackUniversalTemplates();
        }
    }

    
    private List<ConditionTemplate> generateAISpecificTemplates(ManagedResource resource) {
        log.info("AI 특화 조건 생성: {}", resource.getResourceIdentifier());
        
        
        String parameterTypes = resource.getParameterTypes();
        log.warn("DEBUG - AutoConditionTemplateService 파라미터 체크: resourceIdentifier={}, parameterTypes='{}'", 
                 resource.getResourceIdentifier(), parameterTypes);
        
        
        if (parameterTypes == null || parameterTypes.trim().isEmpty() || 
            parameterTypes.equals("[]") || parameterTypes.equals("()")) {
            log.warn("AutoConditionTemplateService - 파라미터 없는 메서드 건너뛰기: {}", resource.getResourceIdentifier());
            return new ArrayList<>(); 
        }
        
        
        
        log.info("신버전 Pipeline 아키텍처로 변경됨 - ConditionTemplateContextRetriever 사용");

        try {
            
            ConditionTemplateGenerationRequest request = ConditionTemplateGenerationRequest.forSpecificTemplate(
                    resource.getResourceIdentifier(), "AUTO_GENERATED");
            
            
            Object rawResponse = aiNativeProcessor.process(request, ConditionTemplateGenerationResponse.class).block();
            ConditionTemplateGenerationResponse response = (ConditionTemplateGenerationResponse) rawResponse;
            
            if (response != null && response.hasTemplates()) {
                String templateResult = response.getTemplateResult();
                log.info("AI 특화 응답: {}", templateResult);
                
                List<ConditionTemplate> templates = parseAITemplateResponse(templateResult, resource.getResourceIdentifier());

                
                if (templates.size() > 1) {
                    log.warn("AI가 {} 개 조건 생성했지만 첫 번째만 사용: {}", templates.size(), resource.getResourceIdentifier());
                    templates = List.of(templates.get(0));
                }

                return templates;
            } else {
                log.warn("특화 조건 템플릿 응답이 비어있음");
                return new ArrayList<>();
            }
            
        } catch (Exception e) {
            log.warn("AI 특화 템플릿 생성 실패: {}", resource.getResourceIdentifier(), e);
            return new ArrayList<>();
        }
    }

    
    private String callAI(String systemPrompt, String userPrompt) {
        try {
            log.info("AINativeIAMOperations를 통한 AI 호출 시작");

            
            if (userPrompt.contains("범용") || userPrompt.contains("업무 환경에서 자주 사용되는")) {
                log.info("범용 조건 템플릿 생성 요청");
                log.info("범용 조건 입력: {}", userPrompt);
                
                
                ConditionTemplateGenerationRequest request = ConditionTemplateGenerationRequest.forUniversalTemplate();
                
                
                Object rawResponse = aiNativeProcessor.process(request, ConditionTemplateGenerationResponse.class).block();
                ConditionTemplateGenerationResponse response = (ConditionTemplateGenerationResponse) rawResponse;
                
                if (response != null && response.hasTemplates()) {
                    String templateResult = response.getTemplateResult();
                    log.info("AI 범용 응답: {}", templateResult);
                    return templateResult;
                } else {
                    log.warn("범용 조건 템플릿 응답이 비어있음");
                    return "[]";
                }
                
            } else {
                log.info("특화 조건 템플릿 생성 요청");
                log.info("특화 조건 입력: {}", userPrompt);
                
                
                ConditionTemplateGenerationRequest request = ConditionTemplateGenerationRequest.forSpecificTemplate(
                        "METHOD", userPrompt);
                
                
                Object rawResponse = aiNativeProcessor.process(request, ConditionTemplateGenerationResponse.class).block();
                ConditionTemplateGenerationResponse response = (ConditionTemplateGenerationResponse) rawResponse;
                
                if (response != null && response.hasTemplates()) {
                    String templateResult = response.getTemplateResult();
                    log.info("AI 특화 응답: {}", templateResult);
                    return templateResult;
                } else {
                    log.warn("특화 조건 템플릿 응답이 비어있음");
                    return "[]";
                }
            }

        } catch (Exception e) {
            log.error("AINativeIAMOperations 호출 실패", e);
            
            return "[]";
        }
    }

    

    
    private List<ConditionTemplate> parseAITemplateResponse(String aiResponse, String sourceMethod) {
        List<ConditionTemplate> templates = new ArrayList<>();

        log.info("AI 응답 파싱 시작 - 소스: {}", sourceMethod);
        log.info("원본 AI 응답: {}", aiResponse);

        try {
            
            String cleanedJson = extractAndCleanJson(aiResponse);
            log.info("정제된 JSON: {}", cleanedJson);

            
            List<Map<String, Object>> rawTemplates = objectMapper.readValue(
                    cleanedJson, new TypeReference<List<Map<String, Object>>>() {});

            log.info("파싱된 템플릿 개수: {} 개", rawTemplates.size());

            for (int i = 0; i < rawTemplates.size(); i++) {
                Map<String, Object> raw = rawTemplates.get(i);
                log.info("템플릿 {} 파싱: {}", i+1, raw);

                try {
                    ConditionTemplate template = ConditionTemplate.builder()
                            .name((String) raw.get("name"))
                            .description((String) raw.get("description"))
                            .spelTemplate((String) raw.get("spelTemplate"))
                            .category((String) raw.getOrDefault("category", "AI 생성"))
                            .classification(parseClassification((String) raw.get("classification")))
                            .sourceMethod(sourceMethod)
                            .isAutoGenerated(true)
                            .templateType("ai_generated")
                            .createdAt(LocalDateTime.now())
                            .build();

                    
                    if (template.getSpelTemplate() != null && !template.getSpelTemplate().trim().isEmpty()) {
                        templates.add(template);
                        log.info("템플릿 추가됨: {} - {}", template.getName(), template.getSpelTemplate());
                    } else {
                        log.warn("빈 SpEL 템플릿으로 인해 제외됨: {}", raw);
                    }
                } catch (Exception itemError) {
                    log.error("템플릿 항목 파싱 실패: {}", raw, itemError);
                }
            }

            log.info("AI 응답 파싱 완료: {} 개 템플릿 최종 생성", templates.size());

        } catch (Exception e) {
            log.error("AI 응답 파싱 실패: {}", aiResponse, e);
            
        }

        return templates;
    }

    
    private String extractAndCleanJson(String aiResponse) {
        if (aiResponse == null || aiResponse.trim().isEmpty()) {
            return "[]";
        }

        
        String cleaned = aiResponse.replaceAll("```json\\s*", "").replaceAll("```\\s*", "");

        
        int startIdx = cleaned.indexOf('[');
        int endIdx = cleaned.lastIndexOf(']');

        if (startIdx != -1 && endIdx != -1 && startIdx < endIdx) {
            return cleaned.substring(startIdx, endIdx + 1).trim();
        }

        
        startIdx = cleaned.indexOf('{');
        endIdx = cleaned.lastIndexOf('}');

        if (startIdx != -1 && endIdx != -1 && startIdx < endIdx) {
            String jsonObject = cleaned.substring(startIdx, endIdx + 1).trim();
            return "[" + jsonObject + "]";
        }

        
        log.warn("AI 응답에서 유효한 JSON을 찾을 수 없음: {}", aiResponse.substring(0, Math.min(100, aiResponse.length())));
        return "[]";
    }

    private ConditionTemplate.ConditionClassification parseClassification(String classification) {
        if (classification == null) return ConditionTemplate.ConditionClassification.CONTEXT_DEPENDENT;

        try {
            return ConditionTemplate.ConditionClassification.valueOf(classification.toUpperCase());
        } catch (Exception e) {
            return ConditionTemplate.ConditionClassification.CONTEXT_DEPENDENT;
        }
    }

    
    private List<ConditionTemplate> generateFallbackUniversalTemplates() {
        log.info("AI 실패로 인한 기본 범용 템플릿 생성");

        List<ConditionTemplate> templates = new ArrayList<>();

        
        templates.add(ConditionTemplate.builder()
                .name("객체 읽기 권한")
                .description("메서드가 반환하는 객체에 대한 읽기 권한 확인")
                .category("권한 기반")
                .classification(ConditionTemplate.ConditionClassification.CONTEXT_DEPENDENT)
                .spelTemplate("hasPermission(#returnObject, 'READ')")
                .sourceMethod("기본")
                .isAutoGenerated(true)
                .templateType("fallback")
                .createdAt(LocalDateTime.now())
                .build());

        
        templates.add(ConditionTemplate.builder()
                .name("인증 확인")
                .description("사용자가 인증되었는지 확인")
                .category("인증 기반")
                .classification(ConditionTemplate.ConditionClassification.UNIVERSAL)
                .spelTemplate("isAuthenticated()")
                .sourceMethod("기본")
                .isAutoGenerated(true)
                .templateType("fallback")
                .createdAt(LocalDateTime.now())
                .build());

        return templates;
    }

    private String generateFallbackUniversalResponse() {
        return """
        [
          {
            "name": "인증된 사용자 확인",
            "description": "사용자가 정상적으로 로그인되어 있는지 확인",
            "spelTemplate": "isAuthenticated()",
            "category": "인증 기반",
            "classification": "UNIVERSAL"
          },
          {
            "name": "완전 인증 확인", 
            "description": "Remember-me가 아닌 완전한 인증 확인",
            "spelTemplate": "isFullyAuthenticated()",
            "category": "인증 기반",
            "classification": "UNIVERSAL"
          },
          {
            "name": "업무시간 접근",
            "description": "오전 9시부터 오후 6시 사이에만 접근 허용",
            "spelTemplate": "T(java.time.LocalTime).now().hour >= 9 and T(java.time.LocalTime).now().hour < 18",
            "category": "시간 기반",
            "classification": "UNIVERSAL"
          },
          {
            "name": "반환 객체 읽기 권한",
            "description": "메서드가 반환하는 객체에 대한 읽기 권한",
            "spelTemplate": "hasPermission(#returnObject, 'READ')",
            "category": "권한 기반", 
            "classification": "CONTEXT_DEPENDENT"
          }
        ]
        """;
    }

    private String generateFallbackSpecificResponse(String methodInfo) {
        
        if (methodInfo.contains("getDocument") || methodInfo.contains("Document")) {
            return """
            [
              {
                "name": "문서 조회 권한",
                "description": "특정 문서 ID에 대한 조회 권한 확인",
                "spelTemplate": "hasPermission(#id, 'DOCUMENT', 'READ')",
                "category": "권한 기반",
                "classification": "CONTEXT_DEPENDENT"
              }
            ]
            """;
        }

        return """
        [
          {
            "name": "기본 실행 권한",
            "description": "메서드 실행에 대한 기본 권한",
            "spelTemplate": "hasPermission(#id, 'RESOURCE', 'EXECUTE')",
            "category": "권한 기반", 
            "classification": "CONTEXT_DEPENDENT"
          }
        ]
        """;
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}