package io.contexa.contexaiam.admin.promptquality.official.model;

public record OfficialRunFailureCause(
        String metricCode,
        String metricName,
        String officialRunId,
        String checkCode,
        String checkLabel,
        String expectedValue,
        String actualValue,
        String source,
        String remediationOwner,
        String problemStatement,
        String rootCause,
        String affectedTarget,
        String impact,
        String remediationHint,
        String reverifyCriterion,
        String issueId,
        String findingId,
        String remediationGroupId) {

    public OfficialRunFailureCause(
            String metricCode,
            String metricName,
            String officialRunId,
            String checkCode,
            String checkLabel,
            String expectedValue,
            String actualValue,
            String source,
            String remediationOwner,
            String problemStatement,
            String rootCause,
            String affectedTarget,
            String impact,
            String remediationHint,
            String reverifyCriterion) {
        this(
                metricCode,
                metricName,
                officialRunId,
                checkCode,
                checkLabel,
                expectedValue,
                actualValue,
                source,
                remediationOwner,
                problemStatement,
                rootCause,
                affectedTarget,
                impact,
                remediationHint,
                reverifyCriterion,
                null,
                null,
                null);
    }

    public OfficialRunFailureCause(
            String metricCode,
            String metricName,
            String officialRunId,
            String checkLabel,
            String expectedValue,
            String actualValue,
            String source,
            String remediationOwner,
            String problemStatement,
            String rootCause,
            String affectedTarget,
            String impact,
            String remediationHint,
            String reverifyCriterion) {
        this(
                metricCode,
                metricName,
                officialRunId,
                null,
                checkLabel,
                expectedValue,
                actualValue,
                source,
                remediationOwner,
                problemStatement,
                rootCause,
                affectedTarget,
                impact,
                remediationHint,
                reverifyCriterion,
                null,
                null,
                null);
    }

    public OfficialRunFailureCause(
            String metricCode,
            String metricName,
            String officialRunId,
            String checkCode,
            String checkLabel,
            String expectedValue,
            String actualValue,
            String source,
            String remediationOwner,
            String rootCause,
            String remediationHint,
            String reverifyCriterion) {
        this(
                metricCode,
                metricName,
                officialRunId,
                checkCode,
                checkLabel,
                expectedValue,
                actualValue,
                source,
                remediationOwner,
                checkLabel,
                rootCause,
                remediationOwner,
                rootCause,
                remediationHint,
                reverifyCriterion,
                null,
                null,
                null);
    }

    public OfficialRunFailureCause(
            String metricCode,
            String metricName,
            String officialRunId,
            String checkLabel,
            String expectedValue,
            String actualValue,
            String source,
            String remediationOwner,
            String rootCause,
            String remediationHint,
            String reverifyCriterion) {
        this(
                metricCode,
                metricName,
                officialRunId,
                null,
                checkLabel,
                expectedValue,
                actualValue,
                source,
                remediationOwner,
                checkLabel,
                rootCause,
                remediationOwner,
                rootCause,
                remediationHint,
                reverifyCriterion,
                null,
                null,
                null);
    }

    public OfficialRunFailureCause(
            String metricCode,
            String metricName,
            String officialRunId,
            String checkLabel,
            String expectedValue,
            String actualValue,
            String source,
            String rootCause,
            String remediationHint,
            String reverifyCriterion) {
        this(
                metricCode,
                metricName,
                officialRunId,
                null,
                checkLabel,
                expectedValue,
                actualValue,
                source,
                source,
                checkLabel,
                rootCause,
                source,
                rootCause,
                remediationHint,
                reverifyCriterion,
                null,
                null,
                null);
    }
}
