package io.contexa.contexaiam.admin.promptquality.official.model;

import java.util.List;
import java.util.Map;

public record RuntimeEvidencePackageDetail(
        RuntimeEvidencePackageSummary summary,
        boolean rawSystemPromptCaptured,
        boolean rawUserPromptCaptured,
        boolean llmSystemPromptCaptured,
        boolean llmUserPromptCaptured,
        boolean baselineSnapshotCaptured,
        boolean ragResultsCaptured,
        String systemPromptPreview,
        String userPromptPreview,
        Map<String, Object> requestFacts,
        Map<String, Object> authState,
        Map<String, Object> promptMetadata,
        Map<String, Object> decision,
        Map<String, Object> baselineSnapshot,
        Map<String, Object> ragResults,
        List<String> missingKnowledgeSignals,
        List<RuntimeEvidenceMissingKnowledgeSignal> missingKnowledgeSignalDetails,
        List<String> qualityWarnings,
        RuntimeEvidencePromptConsistencyResult promptConsistency,
        String systemPromptText,
        String userPromptText) {

    public RuntimeEvidencePackageDetail(
            RuntimeEvidencePackageSummary summary,
            boolean rawSystemPromptCaptured,
            boolean rawUserPromptCaptured,
            boolean llmSystemPromptCaptured,
            boolean llmUserPromptCaptured,
            boolean baselineSnapshotCaptured,
            boolean ragResultsCaptured,
            String systemPromptPreview,
            String userPromptPreview,
            Map<String, Object> requestFacts,
            Map<String, Object> authState,
            Map<String, Object> promptMetadata,
            Map<String, Object> decision,
            Map<String, Object> baselineSnapshot,
            Map<String, Object> ragResults,
            List<String> missingKnowledgeSignals,
            List<String> qualityWarnings,
            RuntimeEvidencePromptConsistencyResult promptConsistency) {
        this(
                summary,
                rawSystemPromptCaptured,
                rawUserPromptCaptured,
                llmSystemPromptCaptured,
                llmUserPromptCaptured,
                baselineSnapshotCaptured,
                ragResultsCaptured,
                systemPromptPreview,
                userPromptPreview,
                requestFacts,
                authState,
                promptMetadata,
                decision,
                baselineSnapshot,
                ragResults,
                missingKnowledgeSignals,
                List.of(),
                qualityWarnings,
                promptConsistency,
                systemPromptPreview,
                userPromptPreview);
    }

    public RuntimeEvidencePackageDetail(
            RuntimeEvidencePackageSummary summary,
            boolean rawSystemPromptCaptured,
            boolean rawUserPromptCaptured,
            boolean llmSystemPromptCaptured,
            boolean llmUserPromptCaptured,
            boolean baselineSnapshotCaptured,
            boolean ragResultsCaptured,
            String systemPromptPreview,
            String userPromptPreview,
            Map<String, Object> requestFacts,
            Map<String, Object> authState,
            Map<String, Object> promptMetadata,
            Map<String, Object> decision,
            Map<String, Object> baselineSnapshot,
            Map<String, Object> ragResults,
            List<String> missingKnowledgeSignals,
            List<RuntimeEvidenceMissingKnowledgeSignal> missingKnowledgeSignalDetails,
            List<String> qualityWarnings,
            RuntimeEvidencePromptConsistencyResult promptConsistency) {
        this(
                summary,
                rawSystemPromptCaptured,
                rawUserPromptCaptured,
                llmSystemPromptCaptured,
                llmUserPromptCaptured,
                baselineSnapshotCaptured,
                ragResultsCaptured,
                systemPromptPreview,
                userPromptPreview,
                requestFacts,
                authState,
                promptMetadata,
                decision,
                baselineSnapshot,
                ragResults,
                missingKnowledgeSignals,
                missingKnowledgeSignalDetails,
                qualityWarnings,
                promptConsistency,
                systemPromptPreview,
                userPromptPreview);
    }

    public RuntimeEvidencePackageDetail(
            RuntimeEvidencePackageSummary summary,
            boolean rawSystemPromptCaptured,
            boolean rawUserPromptCaptured,
            boolean llmSystemPromptCaptured,
            boolean llmUserPromptCaptured,
            boolean baselineSnapshotCaptured,
            boolean ragResultsCaptured,
            String systemPromptPreview,
            String userPromptPreview,
            Map<String, Object> requestFacts,
            Map<String, Object> authState,
            Map<String, Object> promptMetadata,
            Map<String, Object> decision,
            List<String> missingKnowledgeSignals,
            List<String> qualityWarnings,
            RuntimeEvidencePromptConsistencyResult promptConsistency) {
        this(
                summary,
                rawSystemPromptCaptured,
                rawUserPromptCaptured,
                llmSystemPromptCaptured,
                llmUserPromptCaptured,
                baselineSnapshotCaptured,
                ragResultsCaptured,
                systemPromptPreview,
                userPromptPreview,
                requestFacts,
                authState,
                promptMetadata,
                decision,
                Map.of(),
                Map.of(),
                missingKnowledgeSignals,
                List.of(),
                qualityWarnings,
                promptConsistency,
                systemPromptPreview,
                userPromptPreview);
    }

    public RuntimeEvidencePackageDetail(
            RuntimeEvidencePackageSummary summary,
            boolean rawSystemPromptCaptured,
            boolean rawUserPromptCaptured,
            boolean llmSystemPromptCaptured,
            boolean llmUserPromptCaptured,
            String systemPromptPreview,
            String userPromptPreview,
            Map<String, Object> requestFacts,
            Map<String, Object> authState,
            Map<String, Object> promptMetadata,
            Map<String, Object> decision,
            List<String> missingKnowledgeSignals,
            List<String> qualityWarnings) {
        this(
                summary,
                rawSystemPromptCaptured,
                rawUserPromptCaptured,
                llmSystemPromptCaptured,
                llmUserPromptCaptured,
                false,
                false,
                systemPromptPreview,
                userPromptPreview,
                requestFacts,
                authState,
                promptMetadata,
                decision,
                Map.of(),
                Map.of(),
                missingKnowledgeSignals,
                List.of(),
                qualityWarnings,
                RuntimeEvidencePromptConsistencyResult.empty(),
                systemPromptPreview,
                userPromptPreview);
    }
}
