package io.contexa.contexaiam.domain.entity;

import jakarta.persistence.*;
import lombok.*;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(name = "CONDITION_TEMPLATE")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ConditionTemplate implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String name; 

    @Column(nullable = false, length = 2048)
    private String spelTemplate; 

    @Column
    private String category; 

    @Column
    private int parameterCount; 

    @Column(length = 1024)
    private String description; 

    @Column(length = 1024)
    private String requiredTargetType;

    @Column(name = "is_auto_generated")
    @Builder.Default
    private Boolean isAutoGenerated = false; 
    
    @Column(name = "template_type")
    private String templateType; 
    
    @Column(name = "source_method")
    private String sourceMethod; 

    @Column(name = "is_universal")
    @Builder.Default
    private Boolean isUniversal = false; 
    
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "complexity_score")
    @Builder.Default
    private Integer complexityScore = 1; 

    @Column(name = "approval_required")
    @Builder.Default
    private Boolean approvalRequired = false; 

    @Column(name = "context_dependent")
    @Builder.Default
    private Boolean contextDependent = false; 

    @Column(name = "classification")
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private ConditionClassification classification = ConditionClassification.UNIVERSAL; 

    public enum ConditionClassification {
        UNIVERSAL,          
        CONTEXT_DEPENDENT,  
        CUSTOM_COMPLEX      
    }

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
        if (updatedAt == null) {
            updatedAt = LocalDateTime.now();
        }

        if (classification == null) {
            autoClassifyCondition();
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    private void autoClassifyCondition() {
        if (spelTemplate == null) {
            return;
        }

        int score = calculateComplexityScore();
        this.complexityScore = score;

        if (score <= 3) {
            this.classification = ConditionClassification.UNIVERSAL;
            this.contextDependent = false;
            this.approvalRequired = false;
        } else if (score <= 6) {
            this.classification = ConditionClassification.CONTEXT_DEPENDENT;
            this.contextDependent = true;
            this.approvalRequired = false;
        } else {
            this.classification = ConditionClassification.CUSTOM_COMPLEX;
            this.contextDependent = true;
            this.approvalRequired = true;
        }

        // Override: simple but high-impact expressions require approval regardless of complexity
        applyDangerousExpressionOverride();
    }

    private void applyDangerousExpressionOverride() {
        if (spelTemplate == null) {
            return;
        }
        String spel = spelTemplate.toLowerCase().replaceAll("\\s+", "");

        // permitAll grants access to everyone - always requires approval
        if (spel.contains("permitall")) {
            this.approvalRequired = true;
            return;
        }

        // denyAll blocks everything - broad impact requires approval
        if (spel.contains("denyall")) {
            this.approvalRequired = true;
            return;
        }

        // isAuthenticated() alone allows any authenticated user without role checks
        if (spel.contains("isauthenticated()") && !spel.contains("hasrole") &&
                !spel.contains("hasauthority") && !spel.contains("haspermission")) {
            this.approvalRequired = true;
        }
    }

    private int calculateComplexityScore() {
        if (spelTemplate == null || spelTemplate.trim().isEmpty()) {
            return 1;
        }
        
        int score = 1; 
        String spel = spelTemplate.toLowerCase();

        score += countOccurrences(spel, "#");

        score += countOccurrences(spel, "(");

        score += countOccurrences(spel, "&&");
        score += countOccurrences(spel, "||");
        score += countOccurrences(spel, "and");
        score += countOccurrences(spel, "or");

        score += (countOccurrences(spel, "==") + countOccurrences(spel, "!=") + 
                 countOccurrences(spel, ">=") + countOccurrences(spel, "<=")) / 2;

        if (spel.contains("haspermission")) score += 2;
        if (spel.contains("hasrole") || spel.contains("hasauthority")) score += 1;
        if (spel.contains("returnobject")) score += 2;
        if (spel.contains("authentication")) score += 1;
        
        return Math.min(score, 10); 
    }

    private int countOccurrences(String text, String pattern) {
        int count = 0;
        int index = 0;
        while ((index = text.indexOf(pattern, index)) != -1) {
            count++;
            index += pattern.length();
        }
        return count;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ConditionTemplate that)) return false;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
