/*
 * Copyright 2026 The Contexa Project
 *
 * The Contexa Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package io.contexa.contexaiam.repository;

import io.contexa.contexaiam.domain.entity.ConditionTemplate;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

@Repository
public interface ConditionTemplateRepository extends JpaRepository<ConditionTemplate, Long> {

    Optional<ConditionTemplate> findByName(String name);

    List<ConditionTemplate> findByIsAutoGenerated(Boolean isAutoGenerated);

    List<ConditionTemplate> findByIsUniversal(Boolean isUniversal);

    List<ConditionTemplate> findByTemplateType(String templateType);

    List<ConditionTemplate> findBySourceMethod(String sourceMethod);

    @Modifying
    @Transactional(transactionManager = "contexaTransactionManager")
    @Query("DELETE FROM ConditionTemplate ct WHERE ct.isAutoGenerated = :isAutoGenerated")
    void deleteByIsAutoGenerated(@Param("isAutoGenerated") Boolean isAutoGenerated);

    @Modifying
    @Transactional(transactionManager = "contexaTransactionManager")
    @Query("DELETE FROM ConditionTemplate ct WHERE ct.sourceMethod = :sourceMethod")
    void deleteBySourceMethod(@Param("sourceMethod") String sourceMethod);

    List<ConditionTemplate> findByCategory(String category);

    @Query("SELECT ct FROM ConditionTemplate ct WHERE ct.isAutoGenerated = true AND ct.isUniversal = true")
    List<ConditionTemplate> findAutoGeneratedUniversalTemplates();

    @Query("SELECT ct FROM ConditionTemplate ct WHERE ct.isUniversal = true OR ct.templateType LIKE %:entityType%")
    List<ConditionTemplate> findApplicableTemplatesForEntity(@Param("entityType") String entityType);
}
