package io.contexa.contexaiam.repository;

import io.contexa.contexaiam.domain.entity.ConditionTemplate;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

@Repository
public interface ConditionTemplateRepository extends JpaRepository<ConditionTemplate, Long> {

    Optional<ConditionTemplate> findByName(String name);

    List<ConditionTemplate> findByIsAutoGenerated(Boolean isAutoGenerated);

    List<ConditionTemplate> findByIsUniversal(Boolean isUniversal);

    List<ConditionTemplate> findByTemplateType(String templateType);

    List<ConditionTemplate> findBySourceMethod(String sourceMethod);

    @Modifying
    @Transactional
    @Query("DELETE FROM ConditionTemplate ct WHERE ct.isAutoGenerated = :isAutoGenerated")
    void deleteByIsAutoGenerated(@Param("isAutoGenerated") Boolean isAutoGenerated);

    @Modifying
    @Transactional
    @Query("DELETE FROM ConditionTemplate ct WHERE ct.sourceMethod = :sourceMethod")
    void deleteBySourceMethod(@Param("sourceMethod") String sourceMethod);

    List<ConditionTemplate> findByCategory(String category);

    @Query("SELECT ct FROM ConditionTemplate ct WHERE ct.isAutoGenerated = true AND ct.isUniversal = true")
    List<ConditionTemplate> findAutoGeneratedUniversalTemplates();

    @Query("SELECT ct FROM ConditionTemplate ct WHERE ct.isUniversal = true OR ct.templateType LIKE %:entityType%")
    List<ConditionTemplate> findApplicableTemplatesForEntity(@Param("entityType") String entityType);
}
