package io.contexa.contexaiam.admin.promptquality.official.domain;

public record PromptQualityIssue(
        String issueId,
        String severity,
        String title,
        String plainProblem,
        String risk,
        String remediationTarget,
        String nextAction,
        String relatedMetricCode,
        String detectedAt,
        String runId,
        String failedPackageId,
        String evidenceRef,
        String expectedEffect,
        String reRequestMethod,
        String packageId,
        String aggregateRunId,
        String officialRunId,
        String failedCheck,
        String expectedValue,
        String actualValue,
        String source,
        String promptLocation,
        String rootCauseType,
        String productionTargetType,
        String productionTargetRef,
        String productionChangeKind,
        String expectedPromptDelta,
        String reverifyCriterion,
        String httpMethod,
        String findingId,
        String remediationGroupId,
        String findingIds,
        String remediationGroupIds,
        String runtimeActionType,
        String runtimeActionStatus,
        String runtimeActionId,
        String runtimeRuleId,
        String runtimeSlotKey,
        String runtimePromptLocation,
        String runtimeActionLabel,
        String runtimeActionButtonLabel,
        String runtimeActionDescription,
        String runtimeActionPolicyBasis,
        String runtimeActionPolicyId) {

    public PromptQualityIssue(
            String issueId,
            String severity,
            String title,
            String plainProblem,
            String risk,
            String remediationTarget,
            String nextAction,
            String relatedMetricCode,
            String detectedAt,
            String runId,
            String failedPackageId,
            String evidenceRef,
            String expectedEffect,
            String reRequestMethod,
            String packageId,
            String aggregateRunId,
            String officialRunId,
            String failedCheck,
            String expectedValue,
            String actualValue,
            String source,
            String promptLocation,
            String rootCauseType,
            String productionTargetType,
            String productionTargetRef,
            String productionChangeKind,
            String expectedPromptDelta,
            String reverifyCriterion,
            String httpMethod,
            String findingId,
            String remediationGroupId,
            String findingIds,
            String remediationGroupIds) {
        this(
                issueId,
                severity,
                title,
                plainProblem,
                risk,
                remediationTarget,
                nextAction,
                relatedMetricCode,
                detectedAt,
                runId,
                failedPackageId,
                evidenceRef,
                expectedEffect,
                reRequestMethod,
                packageId,
                aggregateRunId,
                officialRunId,
                failedCheck,
                expectedValue,
                actualValue,
                source,
                promptLocation,
                rootCauseType,
                productionTargetType,
                productionTargetRef,
                productionChangeKind,
                expectedPromptDelta,
                reverifyCriterion,
                httpMethod,
                findingId,
                remediationGroupId,
                findingIds,
                remediationGroupIds,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    public PromptQualityIssue(
            String issueId,
            String severity,
            String title,
            String plainProblem,
            String risk,
            String remediationTarget,
            String nextAction,
            String relatedMetricCode,
            String detectedAt,
            String runId,
            String failedPackageId,
            String evidenceRef,
            String expectedEffect,
            String reRequestMethod,
            String packageId,
            String aggregateRunId,
            String officialRunId,
            String failedCheck,
            String expectedValue,
            String actualValue,
            String source,
            String promptLocation,
            String rootCauseType,
            String productionTargetType,
            String productionTargetRef,
            String productionChangeKind,
            String expectedPromptDelta,
            String reverifyCriterion,
            String httpMethod,
            String runtimeActionType,
            String runtimeActionStatus,
            String runtimeActionId,
            String runtimeRuleId,
            String runtimeSlotKey,
            String runtimePromptLocation,
            String runtimeActionLabel,
            String runtimeActionButtonLabel,
            String runtimeActionDescription,
            String runtimeActionPolicyBasis,
            String runtimeActionPolicyId) {
        this(
                issueId,
                severity,
                title,
                plainProblem,
                risk,
                remediationTarget,
                nextAction,
                relatedMetricCode,
                detectedAt,
                runId,
                failedPackageId,
                evidenceRef,
                expectedEffect,
                reRequestMethod,
                packageId,
                aggregateRunId,
                officialRunId,
                failedCheck,
                expectedValue,
                actualValue,
                source,
                promptLocation,
                rootCauseType,
                productionTargetType,
                productionTargetRef,
                productionChangeKind,
                expectedPromptDelta,
                reverifyCriterion,
                httpMethod,
                null,
                null,
                null,
                null,
                runtimeActionType,
                runtimeActionStatus,
                runtimeActionId,
                runtimeRuleId,
                runtimeSlotKey,
                runtimePromptLocation,
                runtimeActionLabel,
                runtimeActionButtonLabel,
                runtimeActionDescription,
                runtimeActionPolicyBasis,
                runtimeActionPolicyId);
    }

    public PromptQualityIssue(
            String issueId,
            String severity,
            String title,
            String plainProblem,
            String risk,
            String remediationTarget,
            String nextAction,
            String relatedMetricCode,
            String detectedAt,
            String runId,
            String failedPackageId,
            String evidenceRef,
            String expectedEffect,
            String reRequestMethod,
            String packageId,
            String aggregateRunId,
            String officialRunId,
            String failedCheck,
            String expectedValue,
            String actualValue,
            String source,
            String promptLocation,
            String rootCauseType,
            String productionTargetType,
            String productionTargetRef,
            String productionChangeKind,
            String expectedPromptDelta,
            String reverifyCriterion) {
        this(
                issueId,
                severity,
                title,
                plainProblem,
                risk,
                remediationTarget,
                nextAction,
                relatedMetricCode,
                detectedAt,
                runId,
                failedPackageId,
                evidenceRef,
                expectedEffect,
                reRequestMethod,
                packageId,
                aggregateRunId,
                officialRunId,
                failedCheck,
                expectedValue,
                actualValue,
                source,
                promptLocation,
                rootCauseType,
                productionTargetType,
                productionTargetRef,
                productionChangeKind,
                expectedPromptDelta,
                reverifyCriterion,
                null,
                null,
                null,
                null,
                null);
    }

    public PromptQualityIssue(
            String issueId,
            String severity,
            String title,
            String plainProblem,
            String risk,
            String remediationTarget,
            String nextAction,
            String relatedMetricCode,
            String detectedAt,
            String runId,
            String failedPackageId,
            String evidenceRef,
            String expectedEffect,
            String reRequestMethod,
            String packageId,
            String aggregateRunId,
            String officialRunId,
            String failedCheck,
            String expectedValue,
            String actualValue,
            String source,
            String promptLocation,
            String rootCauseType,
            String productionTargetType,
            String productionTargetRef,
            String productionChangeKind,
            String expectedPromptDelta,
            String reverifyCriterion,
            String httpMethod) {
        this(
                issueId,
                severity,
                title,
                plainProblem,
                risk,
                remediationTarget,
                nextAction,
                relatedMetricCode,
                detectedAt,
                runId,
                failedPackageId,
                evidenceRef,
                expectedEffect,
                reRequestMethod,
                packageId,
                aggregateRunId,
                officialRunId,
                failedCheck,
                expectedValue,
                actualValue,
                source,
                promptLocation,
                rootCauseType,
                productionTargetType,
                productionTargetRef,
                productionChangeKind,
                expectedPromptDelta,
                reverifyCriterion,
                httpMethod,
                null,
                null,
                null,
                null);
    }

    public PromptQualityIssue(
            String issueId,
            String severity,
            String title,
            String plainProblem,
            String risk,
            String remediationTarget,
            String nextAction,
            String relatedMetricCode,
            String detectedAt,
            String runId,
            String failedPackageId,
            String evidenceRef,
            String expectedEffect,
            String reRequestMethod) {
        this(
                issueId,
                severity,
                title,
                plainProblem,
                risk,
                remediationTarget,
                nextAction,
                relatedMetricCode,
                detectedAt,
                runId,
                failedPackageId,
                evidenceRef,
                expectedEffect,
                reRequestMethod,
                failedPackageId,
                runId,
                null,
                null,
                null,
                null,
                null,
                null,
                "UNKNOWN",
                "MANUAL_REVIEW",
                remediationTarget,
                "MANUAL_REVIEW",
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    public PromptQualityIssue(
            String issueId,
            String severity,
            String title,
            String plainProblem,
            String risk,
            String remediationTarget,
            String nextAction,
            String relatedMetricCode,
            String detectedAt) {
        this(
                issueId,
                severity,
                title,
                plainProblem,
                risk,
                remediationTarget,
                nextAction,
                relatedMetricCode,
                detectedAt,
                null,
                null,
                null,
                null,
                null);
    }
}
