package io.contexa.contexaiam.admin.promptquality.official.domain;

import java.util.List;

public record PromptQualityCertificateView(
        String certificateId,
        String resourceUrl,
        String resourceId,
        String httpMethod,
        String tenantId,
        String promptContractVersion,
        String modelProfile,
        String verifierVersion,
        String state,
        String stateLabel,
        boolean usableForLlmZeroTrust,
        String zeroTrustState,
        String operationalState,
        String issuedAt,
        String expiresAt,
        String promptHash,
        String contextHash,
        int totalMetricCount,
        int verifiedMetricCount,
        int failedMetricCount,
        int missingMetricCount,
        String plainScope,
        String plainMeaning,
        List<String> limitations,
        List<String> evidenceRequestIds,
        List<String> recommendedActions,
        String sealedEvidencePackageId,
        String evidenceSourceType,
        String runtimePromptHash,
        String runtimeSystemPromptHash,
        String runtimeUserPromptHash,
        String runtimeDecisionHash,
        List<String> officialRunIds,
        boolean reverifyRequired) {

    public static final String SOURCE_SEALED_RUNTIME_PACKAGE = "SEALED_RUNTIME_PACKAGE";
    public static final String SOURCE_UNKNOWN = "UNKNOWN";

    public PromptQualityCertificateView(
            String certificateId,
            String resourceUrl,
            String resourceId,
            String httpMethod,
            String tenantId,
            String promptContractVersion,
            String modelProfile,
            String verifierVersion,
            String state,
            String stateLabel,
            boolean usableForLlmZeroTrust,
            String zeroTrustState,
            String operationalState,
            String issuedAt,
            String expiresAt,
            String promptHash,
            String contextHash,
            int totalMetricCount,
            int verifiedMetricCount,
            int failedMetricCount,
            int missingMetricCount,
            String plainScope,
            String plainMeaning,
            List<String> limitations,
            List<String> evidenceRequestIds,
            List<String> recommendedActions
    ) {
        this(
                certificateId,
                resourceUrl,
                resourceId,
                httpMethod,
                tenantId,
                promptContractVersion,
                modelProfile,
                verifierVersion,
                state,
                stateLabel,
                usableForLlmZeroTrust,
                zeroTrustState,
                operationalState,
                issuedAt,
                expiresAt,
                promptHash,
                contextHash,
                totalMetricCount,
                verifiedMetricCount,
                failedMetricCount,
                missingMetricCount,
                plainScope,
                plainMeaning,
                limitations,
                evidenceRequestIds,
                recommendedActions,
                null,
                SOURCE_UNKNOWN,
                null,
                null,
                null,
                null,
                List.of(),
                false
        );
    }

    public PromptQualityCertificateView(
            String certificateId,
            String resourceUrl,
            String resourceId,
            String httpMethod,
            String state,
            String stateLabel,
            boolean usableForLlmZeroTrust,
            String zeroTrustState,
            String operationalState,
            String issuedAt,
            String expiresAt,
            String promptHash,
            String contextHash,
            int totalMetricCount,
            int verifiedMetricCount,
            int failedMetricCount,
            int missingMetricCount,
            String plainScope,
            String plainMeaning,
            List<String> limitations,
            List<String> evidenceRequestIds,
            List<String> recommendedActions,
            String sealedEvidencePackageId,
            String evidenceSourceType,
            String runtimePromptHash,
            String runtimeSystemPromptHash,
            String runtimeUserPromptHash,
            String runtimeDecisionHash,
            List<String> officialRunIds,
            boolean reverifyRequired
    ) {
        this(
                certificateId,
                resourceUrl,
                resourceId,
                httpMethod,
                PromptQualityAssuranceScope.DEFAULT_TENANT_ID,
                PromptQualityAssuranceScope.DEFAULT_PROMPT_CONTRACT_VERSION,
                PromptQualityAssuranceScope.DEFAULT_MODEL_PROFILE,
                PromptQualityAssuranceScope.DEFAULT_VERIFIER_VERSION,
                state,
                stateLabel,
                usableForLlmZeroTrust,
                zeroTrustState,
                operationalState,
                issuedAt,
                expiresAt,
                promptHash,
                contextHash,
                totalMetricCount,
                verifiedMetricCount,
                failedMetricCount,
                missingMetricCount,
                plainScope,
                plainMeaning,
                limitations,
                evidenceRequestIds,
                recommendedActions,
                sealedEvidencePackageId,
                evidenceSourceType,
                runtimePromptHash,
                runtimeSystemPromptHash,
                runtimeUserPromptHash,
                runtimeDecisionHash,
                officialRunIds,
                reverifyRequired
        );
    }

    public PromptQualityCertificateView(
            String certificateId,
            String resourceUrl,
            String resourceId,
            String httpMethod,
            String state,
            String stateLabel,
            boolean usableForLlmZeroTrust,
            String zeroTrustState,
            String operationalState,
            String issuedAt,
            String expiresAt,
            String promptHash,
            String contextHash,
            int totalMetricCount,
            int verifiedMetricCount,
            int failedMetricCount,
            int missingMetricCount,
            String plainScope,
            String plainMeaning,
            List<String> limitations,
            List<String> evidenceRequestIds,
            List<String> recommendedActions,
            String sealedEvidencePackageId,
            String evidenceSourceType,
            String runtimePromptHash,
            String runtimeSystemPromptHash,
            String runtimeUserPromptHash,
            String runtimeDecisionHash,
            boolean reverifyRequired
    ) {
        this(
                certificateId,
                resourceUrl,
                resourceId,
                httpMethod,
                state,
                stateLabel,
                usableForLlmZeroTrust,
                zeroTrustState,
                operationalState,
                issuedAt,
                expiresAt,
                promptHash,
                contextHash,
                totalMetricCount,
                verifiedMetricCount,
                failedMetricCount,
                missingMetricCount,
                plainScope,
                plainMeaning,
                limitations,
                evidenceRequestIds,
                recommendedActions,
                sealedEvidencePackageId,
                evidenceSourceType,
                runtimePromptHash,
                runtimeSystemPromptHash,
                runtimeUserPromptHash,
                runtimeDecisionHash,
                List.of(),
                reverifyRequired);
    }

    public PromptQualityCertificateView(
            String certificateId,
            String resourceUrl,
            String resourceId,
            String httpMethod,
            String tenantId,
            String promptContractVersion,
            String modelProfile,
            String verifierVersion,
            String state,
            String stateLabel,
            boolean usableForLlmZeroTrust,
            String zeroTrustState,
            String operationalState,
            String issuedAt,
            String expiresAt,
            String promptHash,
            String contextHash,
            int totalMetricCount,
            int verifiedMetricCount,
            int failedMetricCount,
            int missingMetricCount,
            String plainScope,
            String plainMeaning,
            List<String> limitations,
            List<String> evidenceRequestIds,
            List<String> recommendedActions,
            String sealedEvidencePackageId,
            String evidenceSourceType,
            String runtimePromptHash,
            String runtimeSystemPromptHash,
            String runtimeUserPromptHash,
            String runtimeDecisionHash,
            boolean reverifyRequired
    ) {
        this(
                certificateId,
                resourceUrl,
                resourceId,
                httpMethod,
                tenantId,
                promptContractVersion,
                modelProfile,
                verifierVersion,
                state,
                stateLabel,
                usableForLlmZeroTrust,
                zeroTrustState,
                operationalState,
                issuedAt,
                expiresAt,
                promptHash,
                contextHash,
                totalMetricCount,
                verifiedMetricCount,
                failedMetricCount,
                missingMetricCount,
                plainScope,
                plainMeaning,
                limitations,
                evidenceRequestIds,
                recommendedActions,
                sealedEvidencePackageId,
                evidenceSourceType,
                runtimePromptHash,
                runtimeSystemPromptHash,
                runtimeUserPromptHash,
                runtimeDecisionHash,
                List.of(),
                reverifyRequired);
    }

    public PromptQualityCertificateView(
            String certificateId,
            String resourceUrl,
            String resourceId,
            String httpMethod,
            String state,
            String stateLabel,
            boolean usableForLlmZeroTrust,
            String zeroTrustState,
            String operationalState,
            String issuedAt,
            String expiresAt,
            String promptHash,
            String contextHash,
            int totalMetricCount,
            int verifiedMetricCount,
            int failedMetricCount,
            int missingMetricCount,
            String plainScope,
            String plainMeaning,
            List<String> limitations,
            List<String> evidenceRequestIds,
            List<String> recommendedActions
    ) {
        this(
                certificateId,
                resourceUrl,
                resourceId,
                httpMethod,
                PromptQualityAssuranceScope.DEFAULT_TENANT_ID,
                PromptQualityAssuranceScope.DEFAULT_PROMPT_CONTRACT_VERSION,
                PromptQualityAssuranceScope.DEFAULT_MODEL_PROFILE,
                PromptQualityAssuranceScope.DEFAULT_VERIFIER_VERSION,
                state,
                stateLabel,
                usableForLlmZeroTrust,
                zeroTrustState,
                operationalState,
                issuedAt,
                expiresAt,
                promptHash,
                contextHash,
                totalMetricCount,
                verifiedMetricCount,
                failedMetricCount,
                missingMetricCount,
                plainScope,
                plainMeaning,
                limitations,
                evidenceRequestIds,
                recommendedActions,
                null,
                SOURCE_UNKNOWN,
                null,
                null,
                null,
                null,
                List.of(),
                false
        );
    }
}
