package io.contexa.contexaiam.admin.promptquality.official.domain;

import io.contexa.contexaiam.admin.promptquality.official.state.PromptQualityStateDescriptor;

public record ProtectableResourceView(
        String resourceId,
        String resourceUrl,
        String httpMethod,
        String criticality,
        boolean verificationRequired,
        boolean sync,
        String ownerField,
        String sourceClassName,
        String sourceMethodName,
        String certificateState,
        String certificateStateLabel,
        String operationalState,
        String operationalStateLabel,
        String latestCertificateId,
        boolean signatureChanged,
        String plainStatus,
        String nextAction,
        String tenantId,
        String promptContractVersion,
        String modelProfile,
        String verifierVersion,
        PromptQualityStateDescriptor runtimeRequestStateDescriptor,
        String latestRuntimeEvidencePackageId,
        String latestRuntimeEvidenceResourceUrl,
        String latestRuntimeEvidenceResourceId,
        String latestRuntimeEvidenceHttpMethod,
        String latestOfficialAggregateRunId,
        String latestOfficialDecision,
        Boolean latestOfficialBlocked,
        Integer latestOfficialPassedMetricCount,
        Integer latestOfficialFailedMetricCount,
        Integer latestOfficialExpectedMetricCount) {

    public ProtectableResourceView(
            String resourceId,
            String resourceUrl,
            String httpMethod,
            String criticality,
            boolean verificationRequired,
            boolean sync,
            String ownerField,
            String sourceClassName,
            String sourceMethodName,
            String certificateState,
            String certificateStateLabel,
            String operationalState,
            String operationalStateLabel,
            String latestCertificateId,
            boolean signatureChanged,
            String plainStatus,
            String nextAction
    ) {
        this(
                resourceId,
                resourceUrl,
                httpMethod,
                criticality,
                verificationRequired,
                sync,
                ownerField,
                sourceClassName,
                sourceMethodName,
                certificateState,
                certificateStateLabel,
                operationalState,
                operationalStateLabel,
                latestCertificateId,
                signatureChanged,
                plainStatus,
                nextAction,
                PromptQualityAssuranceScope.DEFAULT_TENANT_ID,
                PromptQualityAssuranceScope.DEFAULT_PROMPT_CONTRACT_VERSION,
                PromptQualityAssuranceScope.DEFAULT_MODEL_PROFILE,
                PromptQualityAssuranceScope.DEFAULT_VERIFIER_VERSION,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }

    public ProtectableResourceView(
            String resourceId,
            String resourceUrl,
            String httpMethod,
            String criticality,
            boolean verificationRequired,
            boolean sync,
            String ownerField,
            String sourceClassName,
            String sourceMethodName,
            String certificateState,
            String certificateStateLabel,
            String operationalState,
            String operationalStateLabel,
            String latestCertificateId,
            boolean signatureChanged,
            String plainStatus,
            String nextAction,
            String tenantId,
            String promptContractVersion,
            String modelProfile,
            String verifierVersion
    ) {
        this(
                resourceId,
                resourceUrl,
                httpMethod,
                criticality,
                verificationRequired,
                sync,
                ownerField,
                sourceClassName,
                sourceMethodName,
                certificateState,
                certificateStateLabel,
                operationalState,
                operationalStateLabel,
                latestCertificateId,
                signatureChanged,
                plainStatus,
                nextAction,
                tenantId,
                promptContractVersion,
                modelProfile,
                verifierVersion,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }

    public ProtectableResourceView(
            String resourceId,
            String resourceUrl,
            String httpMethod,
            String criticality,
            boolean verificationRequired,
            boolean sync,
            String ownerField,
            String sourceClassName,
            String sourceMethodName,
            String certificateState,
            String certificateStateLabel,
            String operationalState,
            String operationalStateLabel,
            String latestCertificateId,
            boolean signatureChanged,
            String plainStatus,
            String nextAction,
            String tenantId,
            String promptContractVersion,
            String modelProfile,
            String verifierVersion,
            PromptQualityStateDescriptor runtimeRequestStateDescriptor) {
        this(
                resourceId, resourceUrl, httpMethod, criticality, verificationRequired, sync, ownerField,
                sourceClassName, sourceMethodName, certificateState, certificateStateLabel, operationalState,
                operationalStateLabel, latestCertificateId, signatureChanged, plainStatus, nextAction,
                tenantId, promptContractVersion, modelProfile, verifierVersion, runtimeRequestStateDescriptor,
                null, null, null, null, null, null, null, null, null, null);
    }}