dependencies {
    implementation project(':spring-boot-starter-contexa')
    implementation platform("org.springframework.ai:spring-ai-bom:1.1.2")
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation 'org.springframework.ai:spring-ai-starter-model-anthropic'
    implementation 'org.springframework.ai:spring-ai-starter-model-ollama'
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootJar.enabled = true
jar.enabled = true

springBoot {
    mainClass = 'io.contexa.contexastarted.ContexaStartedApplication'
}

tasks.named('resolveMainClassName') {
    enabled = false
}

tasks.named('bootRun') {
    mainClass = 'io.contexa.contexastarted.ContexaStartedApplication'
}

tasks.named('bootJar') {
    mainClass = 'io.contexa.contexastarted.ContexaStartedApplication'
}

