/*
 * Copyright 2026 The Contexa Project
 *
 * The Contexa Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package io.contexa.contexaiam.domain.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.HashMap;
import java.util.Map;

@Data
@AllArgsConstructor
public class AutoGeneratedTemplate {
    private String name;
    private String description;
    private String spelTemplate;
    private String templateType;
    private String sourceMethod;
    private boolean isUniversal;
    private Map<String, Object> metadata;

    public AutoGeneratedTemplate(String name, String description, String spelTemplate,
                                 String templateType, String sourceMethod, boolean isUniversal) {
        this.name = name;
        this.description = description;
        this.spelTemplate = spelTemplate;
        this.templateType = templateType;
        this.sourceMethod = sourceMethod;
        this.isUniversal = isUniversal;
        this.metadata = new HashMap<>();
    }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getSpelTemplate() { return spelTemplate; }
    public void setSpelTemplate(String spelTemplate) { this.spelTemplate = spelTemplate; }
    public String getTemplateType() { return templateType; }
    public void setTemplateType(String templateType) { this.templateType = templateType; }
    public String getSourceMethod() { return sourceMethod; }
    public void setSourceMethod(String sourceMethod) { this.sourceMethod = sourceMethod; }
    public boolean isUniversal() { return isUniversal; }
    public void setUniversal(boolean universal) { isUniversal = universal; }
    public Map<String, Object> getMetadata() { return metadata; }
    public void setMetadata(Map<String, Object> metadata) { this.metadata = metadata; }
}