package io.contexa.contexacommon.mcp.permit;

import java.time.LocalDateTime;
import java.util.Map;

public record PermitIssueRequest(
        String requestId,
        String permitId,
        String approvalId,
        String incidentId,
        String sessionId,
        String tenantId,
        String userId,
        String toolName,
        String requiredScope,
        String executionClass,
        String argumentsHash,
        String riskLevel,
        Double riskScore,
        Double confidence,
        String zeroTrustAction,
        String contextBindingHash,
        String actorType,
        String executionMode,
        String executionId,
        String delegationId,
        String taskPurpose,
        String approvedScopes,
        String actionApprovalCategory,
        String executionContinuityFingerprint,
        LocalDateTime expiresAt,
        Map<String, Object> metadata) {

    public PermitIssueRequest(
            String requestId,
            String permitId,
            String approvalId,
            String incidentId,
            String sessionId,
            String tenantId,
            String userId,
            String toolName,
            String requiredScope,
            String executionClass,
            String argumentsHash,
            String riskLevel,
            Double riskScore,
            Double confidence,
            String zeroTrustAction,
            String contextBindingHash,
            String actorType,
            String executionMode,
            String executionId,
            String delegationId,
            String taskPurpose,
            String approvedScopes,
            LocalDateTime expiresAt,
            Map<String, Object> metadata) {
        this(
                requestId,
                permitId,
                approvalId,
                incidentId,
                sessionId,
                tenantId,
                userId,
                toolName,
                requiredScope,
                executionClass,
                argumentsHash,
                riskLevel,
                riskScore,
                confidence,
                zeroTrustAction,
                contextBindingHash,
                actorType,
                executionMode,
                executionId,
                delegationId,
                taskPurpose,
                approvedScopes,
                null,
                null,
                expiresAt,
                metadata
        );
    }
}