/*
 * Copyright 2026 The Contexa Project
 *
 * The Contexa Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package io.contexa.contexacommon.mcp.permit;

import java.time.LocalDateTime;
import java.util.Map;

public record PermitIssueRequest(
        String requestId,
        String permitId,
        String approvalId,
        String incidentId,
        String sessionId,
        String tenantId,
        String userId,
        String toolName,
        String requiredScope,
        String executionClass,
        String argumentsHash,
        String riskLevel,
        Double riskScore,
        Double confidence,
        String zeroTrustAction,
        String contextBindingHash,
        String actorType,
        String executionMode,
        String executionId,
        String delegationId,
        String taskPurpose,
        String approvedScopes,
        String actionApprovalCategory,
        String executionContinuityFingerprint,
        String subjectType,
        String protocolType,
        String protocolVersion,
        String chainId,
        Integer chainDepth,
        String attestationState,
        LocalDateTime expiresAt,
        Map<String, Object> metadata) {

    public PermitIssueRequest(
            String requestId,
            String permitId,
            String approvalId,
            String incidentId,
            String sessionId,
            String tenantId,
            String userId,
            String toolName,
            String requiredScope,
            String executionClass,
            String argumentsHash,
            String riskLevel,
            Double riskScore,
            Double confidence,
            String zeroTrustAction,
            String contextBindingHash,
            String actorType,
            String executionMode,
            LocalDateTime expiresAt,
            Map<String, Object> metadata) {
        this(
                requestId,
                permitId,
                approvalId,
                incidentId,
                sessionId,
                tenantId,
                userId,
                toolName,
                requiredScope,
                executionClass,
                argumentsHash,
                riskLevel,
                riskScore,
                confidence,
                zeroTrustAction,
                contextBindingHash,
                actorType,
                executionMode,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                expiresAt,
                metadata
        );
    }

    public PermitIssueRequest(
            String requestId,
            String permitId,
            String approvalId,
            String incidentId,
            String sessionId,
            String tenantId,
            String userId,
            String toolName,
            String requiredScope,
            String executionClass,
            String argumentsHash,
            String riskLevel,
            Double riskScore,
            Double confidence,
            String zeroTrustAction,
            String contextBindingHash,
            String actorType,
            String executionMode,
            String executionId,
            String delegationId,
            String taskPurpose,
            String approvedScopes,
            LocalDateTime expiresAt,
            Map<String, Object> metadata) {
        this(
                requestId,
                permitId,
                approvalId,
                incidentId,
                sessionId,
                tenantId,
                userId,
                toolName,
                requiredScope,
                executionClass,
                argumentsHash,
                riskLevel,
                riskScore,
                confidence,
                zeroTrustAction,
                contextBindingHash,
                actorType,
                executionMode,
                executionId,
                delegationId,
                taskPurpose,
                approvedScopes,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                expiresAt,
                metadata
        );
    }

    public PermitIssueRequest(
            String requestId,
            String permitId,
            String approvalId,
            String incidentId,
            String sessionId,
            String tenantId,
            String userId,
            String toolName,
            String requiredScope,
            String executionClass,
            String argumentsHash,
            String riskLevel,
            Double riskScore,
            Double confidence,
            String zeroTrustAction,
            String contextBindingHash,
            String actorType,
            String executionMode,
            String executionId,
            String delegationId,
            String taskPurpose,
            String approvedScopes,
            String actionApprovalCategory,
            String executionContinuityFingerprint,
            LocalDateTime expiresAt,
            Map<String, Object> metadata) {
        this(
                requestId,
                permitId,
                approvalId,
                incidentId,
                sessionId,
                tenantId,
                userId,
                toolName,
                requiredScope,
                executionClass,
                argumentsHash,
                riskLevel,
                riskScore,
                confidence,
                zeroTrustAction,
                contextBindingHash,
                actorType,
                executionMode,
                executionId,
                delegationId,
                taskPurpose,
                approvedScopes,
                actionApprovalCategory,
                executionContinuityFingerprint,
                null,
                null,
                null,
                null,
                null,
                null,
                expiresAt,
                metadata
        );
    }
}
