/*
 * Copyright 2026 The Contexa Project
 *
 * The Contexa Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package io.contexa.contexacommon.mcp.permit;

public record PermitValidationResponse(
        boolean allowed,
        String permitId,
        String reason,
        String toolName,
        String requiredScope,
        String requestId,
        String approvalId,
        String incidentId,
        String sessionId,
        String executionClass,
        String argumentsHash,
        String tenantId,
        String userId,
        String zeroTrustAction,
        Double riskScore,
        Double confidence,
        String contextBindingHashDigest,
        String actorType,
        String executionMode,
        String riskLevel,
        String executionId,
        String delegationId,
        String taskPurpose,
        String approvedScopes,
        String actionApprovalCategory,
        String executionContinuityFingerprint,
        String subjectType,
        String protocolType,
        String protocolVersion,
        String chainId,
        Integer chainDepth,
        String attestationState) {
    public static PermitValidationResponse allowed(
            String permitId,
            String toolName,
            String requiredScope,
            String requestId,
            String approvalId,
            String incidentId,
            String sessionId,
            String executionClass,
            String argumentsHash,
            String tenantId,
            String userId,
            String zeroTrustAction,
            Double riskScore,
            Double confidence,
            String contextBindingHashDigest,
            String actorType,
            String executionMode,
            String riskLevel) {
        return allowed(
                permitId,
                toolName,
                requiredScope,
                requestId,
                approvalId,
                incidentId,
                sessionId,
                executionClass,
                argumentsHash,
                tenantId,
                userId,
                zeroTrustAction,
                riskScore,
                confidence,
                contextBindingHashDigest,
                actorType,
                executionMode,
                riskLevel,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }

    public static PermitValidationResponse allowed(
            String permitId,
            String toolName,
            String requiredScope,
            String requestId,
            String approvalId,
            String incidentId,
            String sessionId,
            String executionClass,
            String argumentsHash,
            String tenantId,
            String userId,
            String zeroTrustAction,
            Double riskScore,
            Double confidence,
            String contextBindingHashDigest,
            String actorType,
            String executionMode,
            String riskLevel,
            String executionId,
            String delegationId,
            String taskPurpose,
            String approvedScopes,
            String actionApprovalCategory,
            String executionContinuityFingerprint) {
        return allowed(
                permitId,
                toolName,
                requiredScope,
                requestId,
                approvalId,
                incidentId,
                sessionId,
                executionClass,
                argumentsHash,
                tenantId,
                userId,
                zeroTrustAction,
                riskScore,
                confidence,
                contextBindingHashDigest,
                actorType,
                executionMode,
                riskLevel,
                executionId,
                delegationId,
                taskPurpose,
                approvedScopes,
                actionApprovalCategory,
                executionContinuityFingerprint,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }

    public static PermitValidationResponse allowed(
            String permitId,
            String toolName,
            String requiredScope,
            String requestId,
            String approvalId,
            String incidentId,
            String sessionId,
            String executionClass,
            String argumentsHash,
            String tenantId,
            String userId,
            String zeroTrustAction,
            Double riskScore,
            Double confidence,
            String contextBindingHashDigest,
            String actorType,
            String executionMode,
            String riskLevel,
            String executionId,
            String delegationId,
            String taskPurpose,
            String approvedScopes,
            String actionApprovalCategory,
            String executionContinuityFingerprint,
            String subjectType,
            String protocolType,
            String protocolVersion,
            String chainId,
            Integer chainDepth,
            String attestationState) {
        return new PermitValidationResponse(
                true,
                permitId,
                null,
                toolName,
                requiredScope,
                requestId,
                approvalId,
                incidentId,
                sessionId,
                executionClass,
                argumentsHash,
                tenantId,
                userId,
                zeroTrustAction,
                riskScore,
                confidence,
                contextBindingHashDigest,
                actorType,
                executionMode,
                riskLevel,
                executionId,
                delegationId,
                taskPurpose,
                approvedScopes,
                actionApprovalCategory,
                executionContinuityFingerprint,
                subjectType,
                protocolType,
                protocolVersion,
                chainId,
                chainDepth,
                attestationState
        );
    }

    public static PermitValidationResponse allowed(
            String permitId,
            String toolName,
            String requiredScope,
            String requestId,
            String approvalId,
            String incidentId,
            String sessionId,
            String executionClass,
            String argumentsHash,
            String tenantId,
            String userId,
            String zeroTrustAction,
            Double riskScore,
            Double confidence,
            String contextBindingHashDigest,
            String actorType,
            String executionMode,
            String riskLevel,
            String executionId,
            String delegationId,
            String taskPurpose,
            String approvedScopes) {
        return allowed(
                permitId,
                toolName,
                requiredScope,
                requestId,
                approvalId,
                incidentId,
                sessionId,
                executionClass,
                argumentsHash,
                tenantId,
                userId,
                zeroTrustAction,
                riskScore,
                confidence,
                contextBindingHashDigest,
                actorType,
                executionMode,
                riskLevel,
                executionId,
                delegationId,
                taskPurpose,
                approvedScopes,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }

    public static PermitValidationResponse denied(String reason) {
        return new PermitValidationResponse(
                false,
                null,
                reason,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }
}
